'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _16386858_hispanic_cartoon_professor_woman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16386858-hispanic-cartoon-professor-woman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _16386858_hispanic_cartoon_professor_woman1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16386858-hispanic-cartoon-professor-woman1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _227_2274986_student_clipart_highschool_teen_girl_cartoon_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("227-2274986_student-clipart-highschool-teen-girl-cartoon-png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3_343() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3-343", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _636203270057692760() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("636203270057692760", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _68874240_cute_and_clever_smiling_young_asian_school_student_boy_with_book_cartoon_style_illustration_isolated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("68874240-cute-and-clever-smiling-young-asian-school-student-boy-with-book-cartoon"& _ 
                        "-style-illustration-isolated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _77969422_vector_cartoon_student_girl_graduate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("77969422-vector-cartoon-student-girl-graduate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _94315122_girl_chemist_character_female_scientist_in_white_coat_holding_test_flask_vector_illustration_on_a_wh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("94315122-girl-chemist-character-female-scientist-in-white-coat-holding-test-flask"& _ 
                        "-vector-illustration-on-a-wh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cartoon_professor_thumb_up_vector_7770389() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cartoon-professor-thumb-up-vector-7770389", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chalkboard_and_professor_college_or_university_vector_21245936() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chalkboard-and-professor-college-or-university-vector-21245936", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Exam_tips_for_parents() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exam-tips-for-parents", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property girl_holding_book_isolated_cartoon_character_elementary_school_student_with_backpack_71593_230() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("girl-holding-book-isolated-cartoon-character-elementary-school-student-with-backp"& _ 
                        "ack_71593-230", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shutterstock_610161122_685x368() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutterstock_610161122-685x368", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Untitled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property young_female_teacher_near_blackboard_teaching_vector_16708082() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("young-female-teacher-near-blackboard-teaching-vector-16708082", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property تراریوم_باغ_شیشه_ای_گل_Traryvm_6_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("تراریوم باغ شیشه ای گل Traryvm(6)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property نقاشی_روز_دانش_آموز_30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("نقاشی-روز-دانش-آموز-30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property نقاشی_روز_دانش_آموز_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("نقاشی-روز-دانش-آموز-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
